name: Build and deploy Python app to Azure Web App - univacai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Güncellenmiş versiyon

      - name: Set up Python version
        uses: actions/setup-python@v2  # v1'den v2'ye güncellenmiş versiyon
        with:
          python-version: '3.11'  # Python sürümünüz

      # Sanal ortam adımlarını ve diğer adımları ekleyin
      # ...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      # Azure'a dağıtımı gerçekleştiren adım
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'univacai'  # Azure Web App adınız
          slot-name: 'Production'  # Eğer bir deployment slot kullanıyorsanız
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CCE45753191D4710815642A2D70D4930 }}