  # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
  # More GitHub Actions for Azure: https://github.com/Azure/actions
  # More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - univacai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Eylemi güncellenmiş sürümle kullan

      - name: Set up Python version
        uses: actions/setup-python@v3  # Python kurulum eylemini güncellenmiş sürümle kullan
        with:
          python-version: '3.11'

      - name: Check current directory and list files
        run: |
          pwd
          ls -l
        
      - name: Cache some dependencies
        uses: actions/cache@v3
        with: 
          path: |
            venv
            reqs.txt
          key: ${{ runner.os }}-venv-${{ hashFiles('**/reqs.txt') }}
          restore-keys : |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        run: pip install -r reqs.txt  # Bağımlılıkları yükle

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x \*venv/\* \*__pycache__/\* \*.git/\* \*node_modules/\*  # Sanal ortam ve gereksiz dosyaları hariç tut

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'univacai'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CCE45753191D4710815642A2D70D4930 }}